// Generated by CoffeeScript 1.4.0
var data, gameOn, io;

io = require('socket.io').listen(8080);

data = {};

gameOn = false;

io.sockets.on('connection', function(socket) {
  var count, item;
  io.sockets.emit('debug', {
    message: 'received'
  });
  data[socket.id] = {
    player: '',
    position: [0.0, 0.0]
  };
  if (data.length === 1) {
    data[socket.id].player = "catch me";
  } else {
    data[socket.id].player = "I'll catch you";
    data[socket.id].position[0] += 0.0001;
    data[socket.id].position[1] += 0.0001;
  }
  console.log("data item:");
  console.log(data);
  count = 0;
  for (item in data) {
    count++;
  }
  console.log(count);
  if (count > 1) {
    console.log("emit gameon");
    gameOn = true;
    console.log(data);
    io.sockets.emit('gameon', data);
  }
  socket.on('whoami', function() {
    return socket.emit('id', socket.id);
  });
  socket.on('newgame', function() {
    console.log("new game requested");
    return socket.emit('ok');
  });
  socket.on('joingame', function() {
    console.log("joingame requested");
    return socket.emit('ok');
  });
  return socket.on('position', function(position) {
    data[socket.id].position = position;
    return console.log("Position received " + data[socket.id].position);
  });
});
