// Generated by CoffeeScript 1.4.0
var io;

io = require('socket.io').listen(8080);

io.sockets.on('connection', function(socket) {
  io.sockets.emit('debug', {
    message: 'received'
  });
  socket.on('newgame', function() {
    console.log("new game requested");
    return socket.emit('ok');
  });
  return socket.on('joingame', function() {
    console.log("joingame requested");
    return socket.emit('ok');
  });
});
